### ISSUE TITLE
Project generator omits configurations properties

### ISSUE THREAD

**Issue by dsimansk** [syndesisio/syndesis-rest#469] opened 2017-07-28 08:39 UTC
Integration source code: https://github.com/dsimansk/kitchensink-test/commit/41f9c70737505eb692fb9501f9da8e310b9e742f

I've tried to create simple Twitter Search to HTTP POST integration, as can be seen in the generated steps, but any other parameters aren't present. E.g. hostname, path, port, for [the refence](https://github.com/syndesisio/connectors/blob/master/connectors/http-post-connector/src/main/resources/camel-connector.json#L18-L19)

JsonDB has only one property and that's httpUri
```json
    "action": {
        "description": "Call a service that is internal (within your company) or external (on the internet) by specifying the service's URL",
        "camelConnectorGAV": "io.syndesis:http-post-connector:0.4.5",
        "camelConnectorPrefix": "http-post",
        "inputDataShape": {
          "kind": "any"
        },
        "outputDataShape": {
          "kind": "any"
        },
        "id": "io.syndesis:http-post-connector:latest",
        "name": "HTTP POST",
        "properties": {
          "httpUri": {
            "kind": "path",
            "displayName": "Http Uri",
            "group": "producer",
            "label": "producer",
            "required": true,
            "type": "string",
            "javaType": "java.net.URI",
            "deprecated": false,
            "secret": false,
            "componentProperty": false,
            "description": "The url of the HTTP endpoint to call."
          }
        }
      },
      "connection": {
        "connectorId": "http",
        "configuredProperties": {},
        "options": {},
        "icon": "fa-globe",
        "description": "HTTP Connection",
        "lastUpdated": 1492095344060,
        "createdDate": 1492095344060,
        "id": "3",
        "tags": ["example", "test"],
        "name": "HTTP Example"
      },
      "stepKind": "endpoint",
      "configuredProperties": {
        "httpUri": "kitchensink-service:8080/mirror/post"
      }
```

**Comment by zregvart** [comment] 2017-07-28 08:47
We need to:
 - see what (connection/endpoint) properties we want citizen users to set on HTTP connections
 - what are we doing with global/component options (application.properties?) how does citizen user define those?

**Comment by jimmidyson** [comment] 2017-07-28 08:52
The problem is the committed [deployment.json](https://github.com/syndesisio/syndesis-rest/blob/9782eb75b6c66a189c45ebbadd8b94e35b71d3dc/dao/src/main/resources/io/syndesis/dao/deployment.json#L1146-L1184) doesn't have the correct properties compared to the latest connector so this match leads to `httpUri` being dropped as it's not a valid property according to the [connector definition](https://github.com/syndesisio/connectors/blob/master/connectors/http-post-connector/src/main/resources/camel-connector.json#L18-L19) and the other properties aren't set at all, hence the empty configuration in the integration source code.

We do need to generate the deployment from the connector definitions somehow rather than this error prone manual updating of the deployment.json.

**Closed** 2018-03-26 08:45 UTC
Labels: bug
